### ISSUE TITLE
Support production deployment of Lyra

### ISSUE THREAD

**Issue by kadamwhite** [uwdata/lyra#267]
### Description
#266 removes the legacy build steps for minifying CSS and JS. These processes should be added back in to the build, preferably integrated with the webpack build & webpack dev server, in such a way that `webpack -p` produces a production build.
### Tasks
- [ ] Research whether Webpack can be configured to use `.min.js` extensions on `--production`-mode build, to allow files to live side-by-side
- [ ] Research how to integrate sass build into webpack (possibly w/ HMR integration)
- [ ] Coordinate with @arvind and @deathbearbrown to identify how a "production" build can be integrated into a `gh-pages` branch deployment

**Comment by arvind** [comment]
Available thanks to #363 (and subsequent bug fixes). Thanks @kadamwhite!
